name: macro-beans
channels:
  - conda-forge
dependencies:
  - python=3.10
  - streamlit
  - pymongo
  - pandas
  - pytz
  - plotly
  - pip:
    - ibapi
    - loguru
    - pytest
    - pytest-mock
    - freezegun
