name: macro-beans
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - pyyaml
  - plotly
  - pip:
    - yfinance
    - scikit-learn
    - loguru
    - pytest
    - pytest-mock
    - freezegun
